### ISSUE TITLE
login silently fails if account is unknown

### ISSUE THREAD

**Issue by xat** [versumstudios/report-bugs#1]
**Describe the bug**

login silently fails if the account is not listed here: https://ipfs.io/ipfs/QmW93a5iELUgHpww5qUsBUoQoEmUREBnpdVYpUdbagv6oV/info.json
this results in an endless loop of the on-boarding wizard.

**To Reproduce**

* try to login with an account that is not in the mentioned list
* this will produce the following error in the console (no error shown in the ui, though)
   <img width="1522" alt="Bildschirmfoto 2022-01-13 um 14 20 02" src="https://user-images.githubusercontent.com/182512/149337595-46c0aa72-4463-45f1-8bdb-2fe1ec6ec78f.png">
* the credentials endpoint responds with a uri that points to this error page: https://versum.xyz/api/auth/error?error=..., but the ui doesn't redirect the user to that error page.

 
this here is the full error from the error query parameter:
```
{
   "response":{
      "errors":[
         {
            "extensions":{
               "path":"$.selectionSet.insert_users_one.args.object[0]",
               "code":"constraint-violation"
            },
            "message":"Not-NULL violation. null value in column \"id\" violates not-null constraint"
         }
      ],
      "status":200,
      "headers":{
         
      }
   },
   "request":{
      "query":"\n  mutation insertUserWithAddress($wallet: String!) {\n    insert_users_one(\n      object: { wallets: { data: { is_primary: true, wallet: { data: { address: $wallet, network_type: \"0\" } } } } }\n    ) {\n      id\n    }\n  }\n",
      "variables":{
         "wallet":"XXXXXXXXXXXXXXXX"
      }
   }
}
```

**Expected behavior**
* ui should handle errors correctly
* backend should handle the case when an account is unknown

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 97

**Context**

I tried to login with multiple accounts. It only worked for the account that was in the mentioned list.

**Comment by andrevenancio** [comment]
What is this list?

**Comment by xat** [comment]
there is a link in the storage of one of your smart contracts that points to this list. as to my understanding, it contains a list of all addresses that are allowed to verify on versum, but veqtor will probably know best :)

**Comment by xat** [comment]
@andrevenancio it's fixed now. thanks! :-)
