### ISSUE TITLE
Can't buy swapped token

### ISSUE THREAD

**Issue by benwellei** [versumstudios/report-bugs#10]
**Describe the bug**
Unable to buy token that was for sale. The transaction was rejected before being injected.

**To Reproduce**

The token swap has been totally sold now, so it cannot be reproduced.

1. Go to [Melting n.1](https://versum.xyz/token/versum/139)
2. It was swap ID 219

https://tzkt.io/KT1GyRAJNdizF1nojQz62uGYkx8WFRUJm9X5/storage/75634 
Key 219

**Expected behavior**
Click Collect, and be able to collect.

**Screenshots**

```token_left_amount: 2```
```collect_max_per_tx: 0```

![image](https://user-images.githubusercontent.com/92695220/149372114-04bf1812-0a2d-4307-ad0e-d6e8291b0002.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave
- Version 1.34.80

**Comment by skenaja** [comment]
`collect_max_per_tx` means that there's no limit on how many items can be purchased in one transaction.

Was the failure a FAILWITH? (meaning it ran out?) 

Looking at the [history of the swap](https://api.tzkt.io/v1/bigmaps/75634/keys/219/updates), when there were 2 left (as per screenshot above), it only took 2 blocks to sell out (so less than a minute).
