### ISSUE TITLE
Custom RPC node

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#100]
**Is your feature request related to a problem? Please describe.**

Public RPC nodes can get busy & cause errors during times of network congestion. This leads to errors in Versum tx. Some users have access to their own private nodes, either as paid-for service or running locally on their local machines or a remote host.

**Describe the solution you'd like**

* Allow users to use their own RPC node (eg a custom teztools node, or `http://localhost:8732/` 
* User can choose `Custom` from node list and enter the node address into a text box and save
* Node address saved on user profile
* Add a disclaimer when choosing a custom node. eg `If using custom nodes and node related issues occur, please revert to Versum provided nodes` or something

**Describe alternatives you've considered**

**Additional context**

**Comment by andrevenancio** [comment]
Picking this up! can you remind me the `keep alive` url I can ping to check if a gateaway is working?

**Comment by andrevenancio** [comment]
for reference https://rpc.tzkt.io/mainnet/chains/main/blocks/head/hash

**Comment by andrevenancio** [comment]
done
