### ISSUE TITLE
Add feed preference toggles for NSFW & Photosensitive

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#101]
**Is your feature request related to a problem? Please describe.**

Works tagged as photosensitive or NSFW aren't yet filtered out of feed based on user preferences

**Describe the solution you'd like**
Display on/off toggles for user Feed preferences to switch on or off allowing NSFW / Photosensitive on feed
Default will be to switch off, ie ITEMS with those tags would not be shown on feed
Capture user preferences during onboarding
Allow updating of preferences on feed settings page

**Comment by andrevenancio** [comment]
Done
