### ISSUE TITLE
I can't verify my profile

### ISSUE THREAD

**Issue by bisdvrk** [versumstudios/report-bugs#11]
I've been trying for many hours to verify my profile but I can't in any way possible, can you help me? Is there a way to manually verify my account? here is my wallet tz1QM7phyZACH4bsQ6toC8h7ix5xTtgRzJZy

**Comment by OtavioLobato** [comment]
My profile: https://versum.xyz/user/tz1Pu9DKJiJB8hDoqo54zQDRDSdbPWi7ARZb

**Comment by apauf** [comment]
I have the same problem.
- wallet: tz1V4BJoKoRtUyYVHXn3ARfKe4pGzfJA2gk3
- profil on versum:  https://versum.xyz/user/a_paufler
Thank you in advance.

**Comment by andrevenancio** [comment]
Seems like you need manual verification. Not a bug. Verification just takes time to be done. Up to 24h as it requires data to be added on our database
