### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ItsAJeepThing** [versumstudios/report-bugs#110]
{
  "props": {
    "amount": 1,
    "swap_id": 38155
  },
  "send": {
    "amount": 1000000,
    "mutez": true,
    "storageLimit": 250,
    "gasLimit": 200000
  },
  "error": {
    "errorDetail": {
      "message": "Network Error",
      "name": "Error",
      "stack": "https://versum.xyz/_next/static/chunks/pages/_app-d148502361671eb4.js:1:198444\nhttps://versum.xyz/_next/static/chunks/pages/_app-d148502361671eb4.js:1:193414\na@https://versum.xyz/_next/static/chunks/pages/_app-d148502361671eb4.js:1:65053",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*"
        },
        "url": "https://eu01-node.teztools.net/chains/main/blocks/head",
        "method": "get",
        "responseType": "json"
      },
      "status": null
    },
    "name": "HttpRequestFailed"
  },
  "message": "Error on collect_swap"
}

*Describe the bug**
A clear and concise description of what the bug is.  Third time I have tried to make a purchase.

**To Reproduce**
Steps to reproduce the behavior: attempt to purchase an artwork

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iPhone using safari browser AirGap wallet

**Additional context**

**Comment by andrevenancio** [comment]
Hi @ItsAJeepThing Please choose another rpc node from settings/general
