### ISSUE TITLE
Collect Issue

### ISSUE THREAD

**Issue by ItsAJeepThing** [versumstudios/report-bugs#120]
Follow-up to #110:

I saw that fix before I sent the issue request.

I just tried 3 times on all 4 RPCs.

No Luck.

**Comment by andrevenancio** [comment]
Can you provide steps to reproduce this issue? and also include your wallet address and which token you are trying to collect @ItsAJeepThing

**Comment by ItsAJeepThing** [comment]
All transactions appear to confirm in the AirGap wallet but no interaction with versum except collect error msg

**Comment by andrevenancio** [comment]
Hi @ItsAJeepThing Its been a long journey but I think all issues with AirGap are now fixed. Let me know if its working for you. Drop by our discord if you're still experiencing issues.
