### ISSUE TITLE
429 too many requests (from format filter selection)

### ISSUE THREAD

**Issue by pyglot** [versumstudios/report-bugs#13]
**Description**
The explorer webpage tries to load too many resources too quickly and causes a '429 too many requests' server response, e.g. it's spamming servers.

This is what appears to be happening: The 429s occur particularily in the 'masonry' view explore page, when I set the filters for file formats. My intention is usually to select only 1 format, however I must click to deselect each of the formats and for every format I deselect new queries are immediately sent out thus causing 429. 

**To Reproduce**

1. Check the console log and see errors
2. Go to https://versum.xyz/explore?formats=WEB%3BGIF%3BJPEG%3BPNG%3BMP4%3BMP3%3BWAV%3BSVG%3BGLB using masonry view
2. Click away the file formats *quickly*
3. Click the file formats back again if necessary. 

**Expected behavior**
Do not overload the server with normal use of the interface. 

**Possible fixes**
Could add a direct link on the file format name to select single format thus reducing the number of requests. 
Could add a rate-limiter on the number of requests being sent. 

**Console log**
framework-8957c350a55da097.js:1 GET https://bafybeih2qy6hqvbsa44agy3d2xw6woafpshswlehau2jvoy4jihphclcsa.ipfs.infura-ipfs.io/ 429 (Too Many Requests)

**Desktop:**
Not to relevant but this is what I used:
- OS: WIN10
- Browser: Chrome
- Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by andrevenancio** [comment]
The intention with the filters is that they are aditive to the content you have. if I add the formats without anything selected you will imediatelly have your assets dissapearing. 

By design you need to unselect one by one. Unless you have a better solution? happy to discuss

**Comment by pyglot** [comment]
I agree all formats should be selected initially, showing the currently active search. 

I am thinking clicking the checkmark button should deselect/select as they do, while clicking the text string e.g. 'MP3' would select only that format. The two click spots might need to be separated a bit for that to work nicely. 

I am also thinking it would be better to expand all the format categories by default. Expanding each category is also extra clicks and there are not that many in each category at the moment. 

If the number of formats and categories grow, on could also add checkmarks to the categories. Also there clicking the string could filter to just that category. 

Other options could be to use shift-clicking, etc. but those might not work so well for touch and mobile.

**Comment by andrevenancio** [comment]
I've changed the formats filter so now its empty by default.
