### ISSUE TITLE
Tried to buy artwork and received error

### ISSUE THREAD

**Issue by Franksy44** [versumstudios/report-bugs#138]
**Describe the bug**

I tried to buy artwork for the first time on Versum and received the following error.

{
  "props": {
    "amount": 1,
    "swap_id": 46847
  },
  "send": {
    "amount": 2000000,
    "mutez": true,
    "storageLimit": 250,
    "gasLimit": 200000
  },
  "error": {
    "name": "MissedBlockDuringConfirmationError"
  },
  "message": "Error on collect_swap"
}

Additional my IP seems to have been block from report this issue through discord.

**To Reproduce**

**Expected behavior**

Please could you rectify error so that I can purchase artwork. 

+

Unblock my IP so that I can be invited to Versum Discord server.

Thanks

**Screenshots**

Please see attached file

**Desktop
<img width="1274" alt="Screenshot 2022-05-27 at 09 25 23" src="https://user-images.githubusercontent.com/106367578/170635346-929ec522-e29a-4aee-ac6d-53ecc790a039.png">
 (please complete the following information):**

- Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
Hi, it seems like there was an error on the beacon SDK. Logout and Login back again, that should fix these types of issues on beacon. Let me know if it didn't help. Please drop by our discord and we're happy to help in real time
