### ISSUE TITLE
The claim verification doesn't work

### ISSUE THREAD

**Issue by ruidomorto** [versumstudios/report-bugs#14]
I try a lot of times with all different nodes to claim my verification but it always returns as an error to my wallet, the button to approve request even appears in kukai. I tried to resync etc and even using temple wallet and the same problem is happening.

here my wallet
ruidomorto.tez
tz1RsFrbkJync4shc9ZxfjG4DMLXBDRbLXt9

my twitter profile
https://twitter.com/ruidomorto

If I can have the verification, I'm really excited and anxious to drop my genesis on versum!

**Comment by ruidomorto** [comment]
my profile on versum
https://versum.xyz/user/ruidomorto

**Comment by andrevenancio** [comment]
Hi Rui. It seems like you're a legitimate user. On Discord Chris Randall is approving users manually. Would be interesting to debug this with you and see where the error is coming from hopefully helping other people in the process.
