### ISSUE TITLE
versum dashboard sync problem

### ISSUE THREAD

**Issue by merilaarium** [versumstudios/report-bugs#140]
{
  "props": {
    "userWallet": "tz1eYvZ4nTbxNPBCfuMLGMQXt8YqKVWCiJD6"
  },
  "send": {},
  "error": {
    "errorDetail": {
      "message": "Network Error",
      "name": "Error",
      "stack": "Error: Network Error\n    at e.exports (https://versum.xyz/_next/static/chunks/pages/_app-31f425d652ed43e7.js:1:205059)\n    at b.onerror (https://versum.xyz/_next/static/chunks/pages/_app-31f425d652ed43e7.js:1:200037)\n    at XMLHttpRequest.a (https://versum.xyz/_next/static/chunks/pages/_app-31f425d652ed43e7.js:1:71672)",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*"
        },
        "url": "https://teznode.letzbake.com/chains/main/blocks/head/context/contracts/tz1eYvZ4nTbxNPBCfuMLGMQXt8YqKVWCiJD6/balance",
        "method": "get",
        "responseType": "json"
      },
      "status": null
    },
    "name": "HttpRequestFailed"
  },
  "message": "Error getting balance"
}

**Comment by andrevenancio** [comment]
Hi, it seems like the request to the RPC node timed out after 30 seconds. Log out from Versum, login back again and make sure the RPC node on your settings is either set to Auto or Manual.
