### ISSUE TITLE
Wont let me cancel an offer

### ISSUE THREAD

**Issue by GaiaMusique** [versumstudios/report-bugs#142]
6736 | Mi Señora | ITEM#23407 | Camilovart | 1 | 4 weeks ago | Cancel offer

Versum does not let me cancel this offer and it doesn't let the artist accept my offer either.
Please, cancel it.

https://versum.xyz/token/versum/23407

GaiaMusique

![CamiloVart - La Señora (offer)](https://user-images.githubusercontent.com/107145195/172691999-40134ac8-202b-45a7-a39f-75ef821f044b.JPG)

![Versum error](https://user-images.githubusercontent.com/107145195/172692148-c942863a-72b8-4874-b134-fdcfcebc1155.JPG)

**Comment by GaiaMusique** [comment]
Please fix this. I spent 1 tezo...

**Comment by andrevenancio** [comment]
Hi @GaiaMusique thanks for sharing this through.

I can see that your offer is still there.
That particular error is when you're getting your tezos balance on the dashboard. Which makes me think there is something wrong with your authentication token. The easiest thing to do is to log out and login again.
Once you are on the dashboard page and you are able to see your tezos balance and your materia balance then you know that error is fixed.

If you still have this error after logging out and loggin in as I'm suggesting, then you need to clear your browser cache and you should be good to go.

Apologies it took so long to reply, its normally faster if you could drop by Discord and drop me a line there.

Many thanks

**Comment by skenaja** [comment]
If this is still an issue, please comment here & I'll re-open ticket.
