### ISSUE TITLE
Number of eds doesn't change after burning eds on Objkt

### ISSUE THREAD

**Issue by chrishamer** [versumstudios/report-bugs#143]
Hi folx,
Collected a 2 eds piece on Versum, then burned 1 ed via Objkt and the number of eds on Versum is still the same.
See attached
Thx
![image](https://user-images.githubusercontent.com/49960379/174607278-e0f82d29-79e6-4396-87ca-179192c8dcf6.png)

**Comment by andrevenancio** [comment]
Hi @chrishamer thanks for reporting. This is most likely a cache issue. I can see 1 edition now
https://versum.xyz/token/versum/25277

If the operation has been done in the blockchain, sooner or later it will reflect on our indexer. sometimes it takes a little bit of time to pick up. you can always check https://status.versum.xyz so see how far behind the indexer is.
