### ISSUE TITLE
"Error on collect_swap"

### ISSUE THREAD

**Issue by julianjonker** [versumstudios/report-bugs#145]
**Describe the bug**
Versum reports error on trying to collect token with Temple wallet:
{
  "props": {
    "amount": 1,
    "swap_id": 49661
  },
  "send": {
    "amount": 0,
    "mutez": true,
    "storageLimit": 250,
    "gasLimit": 220000
  },
  "error": {
    "name": "UnknownBeaconError",
    "title": "Aborted",
    "message": "[ABORTED_ERROR]:The action was aborted by the user.",
    "description": "The action was aborted by the user."
  },
  "message": "Error on collect_swap"
}

**To Reproduce**

1. Go to (https://versum.xyz/token/versum/24941)
2. Click on 'Collect for 0 tz'
3. Wallet throws error 'The action was aborted by the user' and versum pop-up as above

**Expected behavior**
I'd expect wallet to ask to confirm transaction

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I can collect tokens on fxhash without a problem

**Comment by andrevenancio** [comment]
please logout and login again to versum. this "unknown beacon error" comes from the beaconSDK which is a 3rd party tool that connects versum to your wallet. Normally for this type of errors logging out and logging in again fixes it.
