### ISSUE TITLE
Error on collect_swap

### ISSUE THREAD

**Issue by userfry92** [versumstudios/report-bugs#146]
**Describe the bug**
{
  "props": {
    "amount": 1,
    "swap_id": 51837
  },
  "send": {
    "amount": 1000000,
    "mutez": true,
    "storageLimit": 250,
    "gasLimit": 220000
  },
  "error": {
    "errorDetail": {
      "message": "Network Error",
      "name": "Error",
      "stack": "Error: Network Error\n    at e.exports (https://versum.xyz/_next/static/chunks/pages/_app-c02a49c54413179d.js:1:176705)\n    at b.onerror (https://versum.xyz/_next/static/chunks/pages/_app-c02a49c54413179d.js:1:171683)\n    at XMLHttpRequest.s (https://versum.xyz/_next/static/chunks/pages/_app-c02a49c54413179d.js:1:57279)",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*"
        },
        "url": "https://eu01-node.teztools.net/chains/main/blocks/head",
        "method": "get",
        "responseType": "json"
      },
      "status": null
    },
    "name": "HttpRequestFailed"
  },
  "message": "Error on collect_swap"
}

**To Reproduce**

1. Go to 'https://versum.xyz/token/versum/25544'
2. Click on 'Collect for 1 TZ'

**Expected behavior**
Expect the transaction to go through and the NFT asset to be in my wallet.

**Screenshots**
![image](https://user-images.githubusercontent.com/108505469/176817560-c31a6d40-8d26-4be5-8e48-8f8f4353f8a4.png)

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [Brave]
- Version [1.40.107]

**Additional context**
First time it's been a problem.

**Comment by andrevenancio** [comment]
Hi @userfry92 seems like this is an issue related to your RPC node. Please logout from versum, login again and then go to settings and change the RPC node. to manual or Auto.
