### ISSUE TITLE
account interface

### ISSUE THREAD

**Issue by ZSonja** [versumstudios/report-bugs#147]
**Describe the bug**
I would like to verify my account but there is no verify button any more in my interface.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Account'
3. Scroll down to 'Verification'
4. See error - no button

**Expected behavior**
Verify button gone.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [MacOS BigSur]
- Browser [Firefox Developer Edition]
- Version [103.0b3]

**Smartphone (please complete the following information):**

**Additional context**
Hi and thank you for your help. Alana (Sonja Zalar)

**Comment by andrevenancio** [comment]
Please login to Discord and check the #verification channel
