### ISSUE TITLE
error minting

### ISSUE THREAD

**Issue by memoakten** [versumstudios/report-bugs#149]
I got an error while minting, and was told to post this error (see below).
I filled in everything as usual, confirmed in Kukai, and got this error. Nothing out of the ordinary as far as I could see. 
After I closed the error, it said minting was successful! but it went back to the minting page.
I checked my profile and it looks like the mint did indeed work
https://versum.xyz/token/versum/27217
Not sure what's going on. 

{
  "props": {
    "amount": "10",
    "infusions": [],
    "max_per_address": 0,
    "metadata": {
      "valueMap": {},
      "keyMap": {}
    },
    "no_transfers_until": null,
    "req_verified_to_own": false,
    "royalties": "100",
    "splits": [
      {
        "address": "tz1Z1pDsbfuF7t6fHfbVxhjhouRemXuREpH5",
        "pct": "1000"
      }
    ]
  },
  "send": {
    "amount": 0,
    "storageLimit": 1000
  },
  "error": {
    "errorDetail": {
      "message": "Network Error",
      "name": "Error",
      "stack": "Error: Network Error\n    at e.exports (https://versum.xyz/_next/static/chunks/pages/_app-84a853453f1e2604.js:1:163398)\n    at m.onerror (https://versum.xyz/_next/static/chunks/pages/_app-84a853453f1e2604.js:1:158376)\n    at XMLHttpRequest.s (https://versum.xyz/_next/static/chunks/pages/_app-84a853453f1e2604.js:1:44310)",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 30000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*"
        },
        "url": "https://eu01-node.teztools.net/chains/main/blocks/head",
        "method": "get",
        "responseType": "json"
      },
      "status": null
    },
    "name": "HttpRequestFailed"
  },
  "message": "Error signing transaction on mint"
}

**Comment by andrevenancio** [comment]
Hi @memo apologies, I've missed this. Next time ping me on twitter or discord. This error is because sometimes (quite often) that particular node fails. You should always check status.versum.xyz In theory if a node is failing we should automatically change to another node, but if it doesn't happen we need to figure out why. Are you still having issues? If so I'll reopen.
