### ISSUE TITLE
Edits and settings on profile disappear (after index lagging?)

### ISSUE THREAD

**Issue by hansverhaegen** [versumstudios/report-bugs#15]
**Describe the bug**
I made some small edits to my profile: added a sentence in the description, changed avatar and profile banner. These changes don't seem to be permanent. Sometimes (after a problem with indexer?) I go back and all changes are gone.

**To Reproduce**

Go to profile
Edit profile
Add a sentence to description
change avatar
change banner
confirm all changes.
Close page, go back (after index problem?)

**Expected behavior**
Changes should be permanent.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS Monterey
- Browser Firfox
- Version 95

**Comment by hansverhaegen** [comment]
Just saw that also some settings seem to be not permament: disabling minimal mode in 'Feed'

**Comment by andrevenancio** [comment]
This is a known issue we announce. we're not keeping settings persistent in order to fix other issues. its likely to take a few days. apologies.

**Comment by hansverhaegen** [comment]
No need to apologize! ;-) I understand perfectly well. Putting bug reports here only to help Versum getting better...

**Comment by hansverhaegen** [comment]
Seem to be fixed now. The description, banner and profile picture nicely appear. Great! I hope it is the case for everybody.
Closing this report.
