### ISSUE TITLE
{   "props": {     "offer_id": 9212   },   "send": {     "amount": 0,     "storageLimit": 250   },   "error": {     "name": "ParametersInvalidBeaconError",     "title": "Parameters Invalid",     "message": "[PARAMETERS_INVALID_ERROR]:Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.",     "description": "Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again."   },   "message": "Error on accept_offer" }

### ISSUE THREAD

**Issue by Devvv4444** [versumstudios/report-bugs#150]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
Thanks for reporting this issue. There are some instructions above to help us to be able to reproduce this error. Let me know if you're able to provide this info to us. thank you.
