### ISSUE TITLE
List collaborations on 'Created' tab as well

### ISSUE THREAD

**Issue by rodrigoplant** [versumstudios/report-bugs#153]
People are not used to click on the 'Collaborations' tab, so they should be listed on the 'Created' tab too (with an observation or a note identifying that it's a collab).

**Comment by andrevenancio** [comment]
Hi Rodrigo. thanks for your report. We considered this when we initially design this feature. Thought there's pro and cons on both approaches we ended up deciding on separating both. We could change it in the future, but for now we're prioritising other features on our roadmap.
