### ISSUE TITLE
Error on collect swap

### ISSUE THREAD

**Issue by Ischl** [versumstudios/report-bugs#156]
{   "props": {     "amount": 1,     "swap_id": "62698"   },   "send": {     "amount": 690000,     "mutez": true,     "storageLimit": 165,     "gasLimit": 79723   },   "error": {     "name": "UnknownBeaconError",     "title": "Aborted",     "message": "[ABORTED_ERROR]:The action was aborted by the user.",     "description": "The action was aborted by the user."   },   "message": "Error on collect_swap" }

**Comment by skenaja** [comment]
"The action was aborted by the user" can usually be resolved by logging out & back in again - let us know if that fails to solve the issue
