### ISSUE TITLE
Problem with board editing 

### ISSUE THREAD

**Issue by apauf** [versumstudios/report-bugs#157]
1. I cannot edit my boards containing artworks minted on TEIA.art in the last couple of days.
    - https://versum.xyz/board/6otefxfVd
    - https://versum.xyz/board/eRt6fqfeOr
2. The artworks on these boards can't be loaded, so I am also not able to edit and delete those.

In both cases I get the following error message:
"Application error: a client-side exception has occurred (see the browser console for more information)."

- I use Chrome browser and cleared the browsing data (history, cookies, cache, etc.)
- I tried to open https://versum.xyz/ in incognito mode
- Also tried to open https://versum.xyz/ with other browsers eg.: Firefox
But I still get the same error.

Thank you in advance.

**Comment by apauf** [comment]
I cannot buy on the secondary market and cannot accept offers on https://versum.xyz/ and https://objkt.com/

error message:
{
  "props": {
    "market": "OBJKTV2",
    "swap_id": "2935528"
  },
  "send": {
    "amount": 3000000,
    "mutez": true
  },
  "error": {
    "name": "UnknownBeaconError",
    "title": "Aborted",
    "message": "[ABORTED_ERROR]:The action was aborted by the user.",
    "description": "The action was aborted by the user."
  },
  "message": "Error on collect_swap"
}

**Comment by skenaja** [comment]
The first error has now been fixed, please can you report back if you're still seeing an error when you edit the board?

The second error is usually caused by beacon sessions timing out after a while - if you log out & back in again, that usually solves things.
