### ISSUE TITLE
Terms of service feedback

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#16]
Feedback from Discord relating to the [ToS v0.0.0](https://github.com/versumstudios/legal/blob/main/terms-of-service-0.0.0.html)

> "Unless otherwise stated, Versum and/or its licensors own the intellectual property rights for all material on Versum."
> 
> First in the above it would be good with a clarification of who is referred to as licensors. I mean the artists still own the copyright and get to say what it is used for and by who? That is the point of adding a license to the contracts, and there is no text anywhere that I'm aware of that we are giving that away to Versum. 
> 
> Second it would be good with a clarification of what material is considere 'on Versum', as it is actually stored elsewhere on tezos, on ipfs, etc. (AFAIK?)
>  
> Then it would be good with a clarification in the below that the following might be absolutely fine if the artist has provided a license for this, e.g. CC-BY for commercial use. Otherwise what is the point of the licenses?
> 
> """You must not:
>  * Republish material from Versum
>  * Sell, rent or sub-license material from Versum
>  * Reproduce, duplicate or copy material from Versum
>  * Redistribute content from Versum"""
> 
> Last, it would probably be smart to add a term on what are the rights of Versum when some work is minted on your contracts, e.g. the rights to display (or not to display) it indefinitely, facilitating trades, etc..
> 
> Just saying this didn't make sense to me at the moment.
>

**Comment by andrevenancio** [comment]
Thanks for raising this issue.
Its kind of hard to read what's a quote, what's a comment, but

licensors refers to people holding the license. the terms state versum and/or.
