### ISSUE TITLE
Incorrect video thumbnail and aspect ratio info

### ISSUE THREAD

**Issue by jonnyscholes** [versumstudios/report-bugs#17]
**Describe the bug**
The mp4 which was uploaded for [this ITEM](https://versum.xyz/token/versum/227) is square 1080x1080.

The thumbnail generated is the wrong aspect ratio [see thumbnail here](https://ipfs.infura.io/ipfs/QmRkwpUUc2dW5ziw89vnmCVTzzzcND2kdN5C5NUQuJ2WtA).

The metadata on the ITEM page reports the dimensions to be 1920x1920 - but it should be 1080x1080 as per the original upload.

**To Reproduce**
I don't think I can reproduce without minting. But if you goto [this ITEM](https://versum.xyz/token/versum/227) you can see the issues mentioned above. 

**Expected behavior**
Thumbnail should match aspect ratio of video.
Dimensions should report dimensions of the originally uploaded video.

**Screenshots**
Incorrect aspect ratio example in feed:
<img width="1489" alt="Screen Shot 2022-01-14 at 8 08 32 am" src="https://user-images.githubusercontent.com/1259367/149409713-9c1ef508-d6d0-48b1-a3ce-209d1dbf4a72.png">

Correct aspect ratio example (video is playing in screenshot):
<img width="1486" alt="Screen Shot 2022-01-14 at 8 11 37 am" src="https://user-images.githubusercontent.com/1259367/149409811-2c51b862-aa8d-4244-9d95-99fb378645d2.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 97.0.4692.71

**Comment by pichiste** [comment]
@jonnyscholes one odd thing is that the resolution also shows up incorrectly when inspecting the original file on MacOS:
<img width="415" alt="Screenshot 2022-01-14 at 08 15 21" src="https://user-images.githubusercontent.com/111979/149548712-688a01d5-0dc8-4065-b599-817c2facbe0e.png">

Will investigate further and report back.

**Comment by andrevenancio** [comment]
Possibly and issue from the artist export! If the computer returns the wrong image we can't do much about it

**Comment by jonnyscholes** [comment]
@pichiste Oh - weird! I have no idea how that happened - thanks for pointing it out.

@andrevenancio Agreed. Other applications do manage to somehow generate a correct preview (Twitter for example) but it's definitely a weird edge case - and I can't even shed light on how I did it. Feel free to close the issue or mark this as wont fix.

Thanks for looking into it 🙏

**Comment by jonnyscholes** [comment]
Dug a little... just out of curiosity 😊

Turns out if you:

1. Take a 1:1 Screen Recording in MacOS which is >1080px in height
2. Open it in Handbrake and select any of their 1080p presets
3. Then Handbrake incorrectly sets the width of the container - but correctly resizes the content.

<img width="1456" alt="Screen Shot 2022-01-20 at 4 23 21 pm" src="https://user-images.githubusercontent.com/1259367/150278993-b5d64099-0f94-4731-a3ba-7187bb81cf4b.png">

<img width="888" alt="Screen Shot 2022-01-20 at 4 28 04 pm" src="https://user-images.githubusercontent.com/1259367/150279112-0d71f6da-a2dc-4650-96d7-4f3721aa3b6a.png">

I'll just use ffmpeg directly from now on 😂

**Comment by pichiste** [comment]
Good to know! Thanks for digging further, it may help someone that runs into the same issue :)

Closing this one out.
