### ISSUE TITLE
verification error on versum site

### ISSUE THREAD

**Issue by leahlaran** [versumstudios/report-bugs#18]
**Describe the bug**
Hello, i have verified on tz profiles with 4 accounts however the on-chain verification is not going through on the versum website.
My address is  tz1hFu8ukDcnZPjxntVXvGsPcvKfcx1sKqRD , i would appreciate some help if it can be done manually please. 
Much appreciated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by skenaja** [comment]
The account is now verified, closing
