### ISSUE TITLE
"Accept offer" button does not get shown - cannot accept offers

### ISSUE THREAD

**Issue by Quasimondo** [versumstudios/report-bugs#19]
**Describe the bug**
The "accept offer" button does not appear in the "Actions" column of "offers" of an item that I minted and own. This did work until yesterday before the site went down since I could already accept several offers.

**To Reproduce**

1. Sync with wallet
2. Browse to the token page of one of my creations (e.g. https://versum.xyz/token/versum/78)
3. Scroll down to 'Offers'
4. 
![image](https://user-images.githubusercontent.com/182098/149475808-de86e6d0-38a0-4a50-b6e6-53c970db7e9e.png)

**Expected behavior**
The "accept offer" button should appear
**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 96.0.4664.110 (Official Build) (64-bit)

Wallet: Temple

**Comment by skenaja** [comment]
Hi @Quasimondo - this has now been fixed, please could you check this is working OK for you?

**Comment by Quasimondo** [comment]
Yes, I just checked and it works fine again - thank you!
