### ISSUE TITLE
ffmpeg 'readFile' error during mint

### ISSUE THREAD

**Issue by loackme** [versumstudios/report-bugs#21]
**Describe the bug**
Unable to mint a gif, getting a ffmpeg error during media encoding.
Error message can be seen below.

**To Reproduce**
1. Go to mint page
2. Upload gif file (tested 900x900 and 1200x1200 resolution, about 1MB) & fill in form
3. Click 'Mint' button

**Expected behavior**
Mint going through

**Screenshots**

<img width="725" alt="Screenshot 2022-01-14 at 15 05 11" src="https://user-images.githubusercontent.com/57089368/149529054-fcbef507-d57a-4d3b-9bb8-e31775e801e8.png">

**Desktop (please complete the following information):**

- OS: Mac OS Monterey 12.0.1
- Browser: Chrome
- Version: 96.0.4664.110 (Official Build) (x86_64)

**Comment by pichiste** [comment]
Fix is deployed. Please report if you continue to have issues.
