### ISSUE TITLE
PDF support for ITEMS

### ISSUE THREAD

**Issue by Theohorsmeier** [versumstudios/report-bugs#22]
I would like to be able to mint PDF files. Many projects on H=N use this file format.

**Describe the solution you'd like**
PDF file, image preview. A PDF viewer on the site is a "nice to have"

**Comment by Theohorsmeier** [comment]
Since this one is still open, maybe better to add it here?

Great PDF support on desktop! On mobile I have one issue:

![image](https://user-images.githubusercontent.com/17555177/152539253-6e197420-1ab0-4922-8793-2ad782584c39.png)

This was in Chrome on Android, the PDF starts zoomed in, and I can't zoom out completely, or pan around to read the document.

**Comment by andrevenancio** [comment]
implemented. closing
