### ISSUE TITLE
$GET parameters not being passed to 'web' OBJKTs iframe

### ISSUE THREAD

**Issue by tenineight** [versumstudios/report-bugs#23]
When viewing OBJKTs of the format 'web' on versum, it seems that the iframe does not pass the defined $GET parameters as can be seen in the screenshot below.

it says **creator=creator&viewer=viewer&objkt=objktid** where there should probably be tez-addresses and an objkt-id.

**To Reproduce**

1. Go to [https://versum.xyz/token/versum/466](https://versum.xyz/token/versum/466) (randomly choosen web OBJKT)
2. Inspect the source code
3. Highlight the iframe

**Expected behavior**
I would expect to have the tezos-address of the creator & viewer + the id of the objkt as values.

**Screenshots**
<img width="1033" alt="Screenshot 2022-01-14 at 21 50 14" src="https://user-images.githubusercontent.com/1213686/149583557-a008fc9d-ba36-4c80-b7f0-9fd532ff0ab9.png">

**Desktop (please complete the following information):**

- OS: macOS 11.5.2 (BigSur)
- Browser: Chrome 96.0.4664.55 (Official Build) (arm64)

**Comment by andrevenancio** [comment]
So just to clarify `OBJKTs` are the name of hicetnunc token. Versum token is calle `Item`. But we are backwards compatible with hicetnunc and once we index them this should be fixed.

**Comment by andrevenancio** [comment]
fixed. should be visible once hicetnunc tokens are indexed.
