### ISSUE TITLE
Lazy loading instead of 'load more'

### ISSUE THREAD

**Issue by stumats** [versumstudios/report-bugs#24]
**Describe the solution you'd like**
auto loading of the feed on scroll seems nicer, and removes need for a button click

**Describe alternatives you've considered**
is it harder to return to exact page placement when lazy load?  Also wonder if one or other method with larger content page would crash browser, esp if lots of active works on it

**Comment by andrevenancio** [comment]
Infinite scroll is a bad ux practice for websites with footers. You will never be able to reach the end. We decided against it early on since a lot of information needed to go in the footer to clear the UI.
