### ISSUE TITLE
Improve mobile display aspect ratio for web objects with aspect ratio set to FILL

### ISSUE THREAD

**Issue by pyglot** [versumstudios/report-bugs#25]
**Description**
I have a web object I minted with the aspect ratio set to "fill". On the PC it occupies most of the screen area however on mobile in portait mode it takes up only about 20% of the screen. For landscape mode it is difficult to scroll down/up, so there needs to be a certain area available no the left and right sides for the user to scroll the page up/down. 

**To Reproduce**

1. Go to ['...'](https://versum.xyz/token/versum/582) in portrait mode on a mobile

**Expected behavior**
The mobile display should take up a large portion of the screen area when the item is set to fill without making it difficult to scroll down to the item details. Adding a full-screen mode or viewing mode without browser banners would help. 

**Screenshot**
Portrait mode
<img src="https://user-images.githubusercontent.com/8835587/149601989-9ea565ce-e55b-4a5e-ab84-7bd273aef75e.png" width=33%>

Landscape mode
<img src="https://user-images.githubusercontent.com/8835587/149602939-c5802523-420d-4adf-93fa-f2dff10ea683.png" width=66%>

**Smartphone (please complete the following information):**

- Device: Galaxy S10
- OS: Android 11
- Browser Chrome
- Version 96

**Comment by andrevenancio** [comment]
Good point!

**Comment by pichiste** [comment]
Thanks for reporting, a solution as been implemented for fill mode on mobile.

We can address the landscape layout in the other issue.
