### ISSUE TITLE
Show number on Created, Owned & Collaborations

### ISSUE THREAD

**Issue by walt-artist** [versumstudios/report-bugs#26]
Would be nice to have a number on the created, owned and collaborations tabs to quickly see how many of each a user has.
Right now you have to click to go to each tab before you see if theres something or not.

![image](https://user-images.githubusercontent.com/85451729/149615754-2ee4accd-be5b-4adf-825e-2d21640e5b34.png)

**Comment by walt-artist** [comment]
This was supposed to be feature request.. But I don't know where to edit that.

**Comment by andrevenancio** [comment]
Hey! Good call! We actually have this feature implemented but I disabled it to test something and then I forgot to enable again 😭

**Comment by andrevenancio** [comment]
done
