### ISSUE TITLE
Item > Market tab - scrollbars appear

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#27]
From Discord:

> I see it on Market page in all browser regardless window size. Here is Brave/Chrome/Vivaldi. Windows 10 on 4K screen with 150% scale setting (in windows screen preferences, not in browser)

![image](https://user-images.githubusercontent.com/510285/149619617-bbd6e59f-4985-46d6-a2d6-138e2213dfc9.png)

Looks like it's related to the scaling

**Comment by andrevenancio** [comment]
God windows sucks... I know there's a way of avoiding this but I need to test it from my windows machine.

**Comment by andrevenancio** [comment]
This should be solved. Scrollbars only show when needed
