### ISSUE TITLE
In the "Splits" list, write profile names when available (+ checkmark if verified) 

### ISSUE THREAD

**Issue by LeithBA** [versumstudios/report-bugs#30]
**Problem**
When consulting the splits list before buying a token to know where our xtz is going, you have to open all addresses one by one in a new tab to see who they belong to. This is kind of frustrating and takes longer than it should.

**Solution**
I think an easy way to solves this would be to write the profile name that belongs to the wallet instead or next to the address.

**Alternative**
An alternative solution would be to write then name in a tooltip when the user hovers over the address.

**Additional context**
![image](https://user-images.githubusercontent.com/34186819/149667067-06ef995a-82b7-435b-86ad-1d44a39f55cb.png)

**Comment by andrevenancio** [comment]
This would be nice, however tezos domains rates their api usage. So its likely that I would have issues enabling this. I have the code to do it, but all the users having this requests done will be an issue.

A probably more elegant solution is having this done behind the scenes on our indexer. @veqtor Is this something already in place?

**Comment by veqtor** [comment]
What about our profile names though?

**Comment by andrevenancio** [comment]
Yeah we could do that too. which at the moment are wallets! ahaha but `user.name` ?

**Comment by andrevenancio** [comment]
After some discussion with the team we will not implement this feature.

This section relates to blockchain information, so displaying the usernames on versum would look a bit weird.
