### ISSUE TITLE
optimize format filter to easier access single formats or single categories

### ISSUE THREAD

**Issue by EMES77** [versumstudios/report-bugs#31]
**Is your feature request related to a problem? Please describe.**
When I want to filter for a specific format like GIF I have to uncheck all other formats manually first.

**Describe the solution you'd like**
It would help to have a "deselect all" option. Also it would be nice to filter for categories.
Only pictures / only video / only 3D / only interactive
Maybe there is even a better solution I don't think of...

Maybe the filter could work that way, that with the first click on a checkbox of one format, all others could be deselected. following selects add onto the first filter. Maybe with a timeout...

**Comment by andrevenancio** [comment]
this has been updated! thanks for your suggestion
