### ISSUE TITLE
Versum doesnt count collectors after 100

### ISSUE THREAD

**Issue by markknol** [versumstudios/report-bugs#32]
**Describe the bug**
Versum doesnt sow or count the collectors after you passed 100 collectors.
I noticed this because it was 100, but got other sales after that.

**To Reproduce**

1. Go to https://versum.xyz/token/versum/410
2. Click on Collectors
3. Observe the count (100)

**Expected behavior**

Show correct number.

---

Personal note; congrats on the launch and this great promising platform. Looking forward to all upcoming features!

**Comment by markknol** [comment]
When you look at the quantity in market tab, you see it is (at moment of writing) 790, out of 1000 editions, which means that 210 are collected. Now some people have collected multiple, but by average not 2 per person.

**Comment by andrevenancio** [comment]
Fixed
