### ISSUE TITLE
User without Materia should receive a warning preventing them from minting

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#35]
**Describe the bug**
Users without Materia don't find out that they can't mint until they get to Wallet tx confirm stage. They get a 'this transaction will fail' message.

**To Reproduce**

pre-requisites: user approved, no materia balance

1. Go to Mint, enter in details
2. click on Mint button

**Expected behavior**
A full-screen warning should appear when a user access `/mint` that they need Materia in order to mint, with a link to the help docs.

**Comment by andrevenancio** [comment]
this has been implemented.
