### ISSUE TITLE
Advanced Swap fails silently depending on input parameters

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#36]
**Describe the bug**
Depending on what you enter as starting/ending price, here are some examples of parameters that don't get accepted. The swap box closes without creating the swap, and there's no error message in the console.

**To Reproduce**

1. Create Advanced swap, end enter the following params

- scenario A: any decimal in the start amount
- scenario B: 10 ed with prices between 2 and 8

**Expected behavior**
- The screen should calculate the appropriate amounts and allow the swap to be created
- Any swap that the advanced swap can't calculate correctly should display an error

**Screenshots**
![advswap](https://user-images.githubusercontent.com/510285/149766572-351d0f6f-ddcf-4f16-a9c6-b896b0fbea40.gif)

**Comment by ofZach** [comment]
+1, I have seen this error (reported this on discord)...

**Comment by visiophone** [comment]
I found that if you swap -1 it works. I swapped 24 (from a 25 ed) and it worked.
Not sure if it happens in all cases

**Comment by vectorz3r0** [comment]
+1, like it shows on the GIF I was trying to swap 15 with start price of 0.25. 
If I try it without any decimals it works just fine and the swap is created.

**Comment by andrevenancio** [comment]
I've added validation for all fields. this should be fixed.

**Comment by garubim** [comment]
I'm not being able to swap using decimals. But no point minting a lot of items if I can't start with a low price. Anyone aware of this error? I know this forum was closed over 2 months ago...
