### ISSUE TITLE
change "seller" on market / offers to "buyers" 

### ISSUE THREAD

**Issue by ofZach** [versumstudios/report-bugs#37]
**Is your feature request related to a problem? Please describe.**

This language (calling the offerer "seller" ) seems wrong to me

<img width="437" alt="Screen Shot 2022-01-17 at 7 02 07 AM" src="https://user-images.githubusercontent.com/142897/149766494-4f85fcb1-6df2-4c22-ae15-1ed13e591d81.png">

here this is someone who seeks to buy not sell.

**Describe the solution you'd like**

change how offers appear in marketplace 

**Describe alternatives you've considered**

the word seller could be something else.  it should just not be "seller" -- for example, offerer, from, etc. 

**Additional context**

https://versum.xyz/token/versum/884

**Comment by andrevenancio** [comment]
You are right. Thanks for this. will deploy a solution today.
