### ISSUE TITLE
UI issues for advanced swap

### ISSUE THREAD

**Issue by ofZach** [versumstudios/report-bugs#38]
**Is your feature request related to a problem? Please describe.**

I had an issue where I did an advanced swap (staggered pricing) which sold really quickly probably within 1-2 minutes, so people who purchased it didn't know what they were paying. 

<img width="318" alt="Screen Shot 2022-01-17 at 7 08 32 AM" src="https://user-images.githubusercontent.com/142897/149767029-c98b5204-b212-457d-8cfc-fad21342b3aa.png">

**Describe the solution you'd like**

I don't know what a good solution is, but maybe if you have a button that says "buy for X" and they can't, they should be alerted to the fact that that price range is out.

**Describe alternatives you've considered**

maybe you need to have all prices available as buttons and then grey out ones that are not available. 

**Additional context**

https://versum.xyz/token/versum/451

**Comment by andrevenancio** [comment]
The price will always show up on their wallet to confirm.

**Comment by ofZach** [comment]
sure!  but I think people see the "buy at x" price and are not really checking their wallet carefully.  it may be better if there's some kind of clear flag about the pricing mechanics or to look so they can be less confused by the situation.  two people messaged me after wondering about it, which makes me a little hesitant to use this feature.

**Comment by andrevenancio** [comment]
Unless we enable something like websockets this will potentially always going to be a problem.

Imagine the scenario:
1) User A open the token detail page and see's a price of 1 tez
2) User B, C and D buy that swap and that increases the price internally on the smart contract.
3) if User A now tries to buy it without a page refresh they still see the same price as they did initially

We need to assess how to handle this edge cases for high profile artists with a lot of demand like you. We need to prioritise this alongside other features and we need to cross reference the impact of webcksockets / pooling solution with our current infrastructure costs. Which at this point less than 2 week's in and having burned through our monthly quota on day 2, I'm not sure of our monthly revenue/expenses ratio is and how would websockets impact it.

Bear with us for a couple of days. this one can be fixed relatively easy on the frontend, but has a behind the scenes impact which at this phase I dont know how much.

**Comment by andrevenancio** [comment]
Hi @ofZach closing this. we introduced slippage which allows users to buy with a bit of a margin above asking price, and then the excess gets returned. https://docs.versum.xyz/faq/slippage/
