### ISSUE TITLE
Profile Galleries not expanding to fullscreen

### ISSUE THREAD

**Issue by babycommando** [versumstudios/report-bugs#40]
**Is your feature request related to a problem? Please describe.**
I know that's probably some next-js css stuff, it likes to containerize stuff. But the displaying of the arts under the profile could be on full scale on computer, would look really good! Unless it was a dev's option.

A solution would be to adjust the flexbox or cssgrid or other css stuff that was made for the profile gallery display.

thanks!

![image](https://user-images.githubusercontent.com/71618056/149802506-2c7045de-8b82-4fac-a8bd-463e7c36273c.png)

**Comment by andrevenancio** [comment]
This is a technical decision aiming at content delivery speed.
If this options is left for the user then user A and user B with different visual options would have to have different cache's
Keeping it small also allow us to load the content faster and waste less bandwidth. Feed's we allow personalisation, but not on user profiles.
