### ISSUE TITLE
the object is minted but isn't shown on my profile

### ISSUE THREAD

**Issue by katotrofimova** [versumstudios/report-bugs#41]
Hey everyone! I've minted an object half an hour ago. It's confirmed by Tez, and shown in my Kukai wallet, but it's still not shown on my Versum profile. Here's my profile https://versum.xyz/user/kato. I guess, it's a bug. Can you please help me?

**Comment by andrevenancio** [comment]
We had indexing issues. Should be fine now

**Comment by katotrofimova** [comment]
Thank you!
