### ISSUE TITLE
Image resizer is changing image colours

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#42]
**Describe the bug**
This Item has less vivid colours on the resized preview images vs the original
https://versum.xyz/token/versum/2227
https://bafybeib2dqccwpgs7km4vozdonzzkkfewbw2heo7znhsyjb7ismw4wdjau.ipfs.infura-ipfs.io/

Original: https://cloudflare-ipfs.com/ipfs/QmdMVnH2xnxD2UDAVCSJECm6P8aqLj6m3qy3hGaH3K9v8w
resized: https://cloudflare-ipfs.com/ipfs/QmPbAnT5sYL6LyZsRWSxnHEoqc9VySYf5mGEZP688sYoSV

**Comment by andrevenancio** [comment]
@pichiste any idea?

**Comment by pichiste** [comment]
Thanks for reporting. This has to do with the color profile of the original image (ProPhoto RGB) being improperly mapped to sRGB:
![Screenshot 2022-01-21 at 05 52 35](https://user-images.githubusercontent.com/111979/150468055-53f5bf85-5643-4c30-afd4-7a4ad5b7f797.png)

Will look further into a fix for this.

In the meantime, if you convert to sRGB before minting you should be good to go.

**Comment by andrevenancio** [comment]
how should we handle this ticket @pichiste close it and add to the documentation that colour profiles are required to be on XYZ format?

**Comment by andrevenancio** [comment]
Has this been fixed @pichiste ? should I close?

**Comment by pichiste** [comment]
Yes it's fixed now
