### ISSUE TITLE
WAV files - no preview/cover image, sound doesn't play

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#43]
**Describe the bug**

Few WAV issues being reported:
1) https://versum.xyz/token/versum/1642 - this wav file is missing a cover image, music doesn't play

2) mint preview doesn't show up (screenshot)
![image](https://user-images.githubusercontent.com/510285/150038548-38eede45-da8f-47b1-9c57-cc4fe4fd8098.png)

**Comment by andrevenancio** [comment]
I've fixed the cover on wav, but something is still off. need more testing.

**Comment by andrevenancio** [comment]
I can't replicate this anymore. Fixed?
