### ISSUE TITLE
Feature: Tips for creators

### ISSUE THREAD

**Issue by Sekuta82** [versumstudios/report-bugs#47]
Adding a tip on top of the asking price for primary and secondary market if you find that the creator under-priced their creation or you want to give more to the creator on secondary sales.
It would help normalizing prices a bit through the market where people can give what they think it's worth.

You could always send some tezos directly to their wallet but showing this in the history will motivate others to do the same.

**Comment by andrevenancio** [comment]
Thanks for your suggestion. At the moment implementing something like this is out of scope. The smart contracts expect the price so sending a different amount will result in invalid transactions.
