### ISSUE TITLE
Load more is retrieving the wrong start index

### ISSUE THREAD

**Issue by codewithfeeling** [versumstudios/report-bugs#49]
I am regularly seeing repeated items after clicking `Load More`. Seems that the start index ID of the next chunk is getting out of whack somehow.

1. Go to the main feed.
2. Click "Load more"
3. Observe repetition

Expected behaviour - there is no repetition

First "Load More"
![image](https://user-images.githubusercontent.com/262516/150347276-5f346d06-a8d5-42a9-92e8-675a7673c780.png)

Second
![image](https://user-images.githubusercontent.com/262516/150347755-2cf42481-b97b-4421-a3ea-382f32ba1a25.png)

Third
![image](https://user-images.githubusercontent.com/262516/150347860-f4007378-8670-4843-96ba-81877e9cf0b4.png)

Using Brave on macOS Monterey (all latest versions)

**Comment by andrevenancio** [comment]
Hey @codewithfeeling is this something that only happens on Vertical filter?

**Comment by veqtor** [comment]
This is a known issue, see the modified feed query from the other day that has a temporal start time, asida from enabling better caching, solves this as well.

**Comment by pichiste** [comment]
This seems to be fixed now
