### ISSUE TITLE
Tag filters break viewing of ITEMs below the 'Load more' fold

### ISSUE THREAD

**Issue by frycomputer** [versumstudios/report-bugs#50]
When using a tag filter (e.g. 'ITEM4ITEM'), after selecting 'Load more', clicking to open an item closes the view of the additional loaded ITEMs — and requires the user to click 'Load more' again to reload up to the same point before the modal view is initiated.

- Add a tag filter
- Select 'Load more'
- choose an ITEM within the second batch of loaded ITEMs

The ITEM view will load briefly and then close, and not be opened again until 'Load more' is selected again

macOS 12.1 , Chrome 97.0.4692.71

**Comment by andrevenancio** [comment]
I've noticed this yesterday too! thanks! super annoying one!

**Comment by pichiste** [comment]
Fixed
