### ISSUE TITLE
ffmpeg Minting Error - PNG file (7MB)

### ISSUE THREAD

**Issue by tnoya001** [versumstudios/report-bugs#53]
Error: ffmpeg.FS('readFile', 'preview_image_2048w.jpg') 
error. Check if the path exists
    at Object.D [as FS] (_next/static/chunks/387.5836c932cf2bbbff.js:1:8651)
    at _next/static/chunks/840.c7362532cba71307.js:1:4903
    at s (main-2f684a5860a4cdc8.js:1:90947)
    at Generator._invoke (main-2f684a5860a4cdc8.js:1:90735)
    at Generator.P.forEach.e.<computed> [as next] (main-2f684a5860a4cdc8.js:1:91370)
    at g (_next/static/chunks/840.c7362532cba71307.js:1:3211)
    at i (_next/static/chunks/840.c7362532cba71307.js:1:3414)

**Comment by pichiste** [comment]
Hi, what OS and browser version are you on?

This error can occur for several reasons, some of which have already been solved but not yet deployed.

A couple of questions:
- Does the filename contain any special characters?
- What are the dimensions of the image?

If you can provide us with the original file so we can test it would be much appreciated. You can DM it to me on the Versum discord server if you prefer not to post it publicly.

**Comment by tnoya001** [comment]
Hi. Thanks for the help. I was using Chrome on Monterey (12.1). Image dimensions are 3000x3000. 

I think it might have been the filename (it had one dash), I wanted to try again with an updated filename, but now the site is prompting me with not having Materia nor being verified (I have Materia and I had already verified my account last week). I will try again tomorrow

**Comment by andrevenancio** [comment]
Has this been fixed @pichiste ? should we close?

**Comment by pichiste** [comment]
It's not clear what the problem is in this case, need more info.

@tnoya001 feel free to re-open with more info if you continue to face this issue.

**Comment by tnoya001** [comment]
Hi. Apologies, I was away from my computer. Yes! Changing the filename worked! Thanks so much for the help. Again, sorry for the delay in confirming the solution with you. Best, TN
