### ISSUE TITLE
verification

### ISSUE THREAD

**Issue by fxhq** [versumstudios/report-bugs#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skenaja** [comment]
I will re-open the ticket if more information is provided.

**Comment by fxhq** [comment]
Hey, I provided so much information. How many more do you want? I also payed for some of this actions. Your "Verification System" is absolut horrible. "Closed" lol Gesendet mit der mobilen Mail AppAm 23.01.22 um 13:28 schrieb skenaja
                
            
            
                
                    Von: "skenaja" ***@***.***>Datum: 23. Januar 2022An: "versumstudios/report-issues" ***@***.***>Cc: "Author" ***@***.***>,"FXHQ" ***@***.***>Betreff: Re: [versumstudios/report-issues] verification (Issue #54)
                
                
I will re-open the ticket if more information is provided.

**Comment by skenaja** [comment]
The only information provided on the [support ticket](https://github.com/versumstudios/report-issues/issues/54) is the word "verification". If you're having issues with verification, please see https://docs.versum.xyz/docs/versum/Verification for requirements. 

The Discord channels #getting-started and #announcements have more information if needed
https://discord.gg/uWjMVUBv

**Comment by fxhq** [comment]
But I verificated my discord, GitHub, twitter, metamask, and so on. I provided like almost everything. Maybe u can have look what else is missing. versum.xyz/user/Gesendet mit der mobilen Mail AppAm 23.01.22 um 18:15 schrieb skenaja
                
            
            
                
                    Von: "skenaja" ***@***.***>Datum: 23. Januar 2022An: "versumstudios/report-issues" ***@***.***>Cc: "FXHQ" ***@***.***>,"Author" ***@***.***>Betreff: Re: [versumstudios/report-issues] verification (Issue #54)
                
                
The only information provided on the support ticket is the word "verification". If you're having issues with verification, please see https://docs.versum.xyz/docs/versum/Verification for requirements.
The Discord channels #getting-started and #announcements have more information if needed
https://discord.gg/uWjMVUBv
