### ISSUE TITLE
500 on status page

### ISSUE THREAD

**Issue by ingenieroariel** [versumstudios/report-bugs#55]
**Describe the bug**
On Jan 23, around 4pm GMT-5 the status page responded with 500 error while the site was down.

Status page needs to work even when the site is down.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
This has been addressed. thanks for reporting
