### ISSUE TITLE
no button to accept collab item

### ISSUE THREAD

**Issue by uzupis** [versumstudios/report-bugs#56]
**Describe the bug**
I created a collecrion of collab items with 15 partners each and split royalties. When my partners open the detail page of the items there is no visible button or other option to accept the item collaboration. For this, the items cannot be swapped. There is also no notification waring about the collab item in the upper right corner.

**To Reproduce**

1. Go to versum.xyz
2. click on mint amd create an nft with 15 collaborators in total each earning 6% except for the creator of the artwork who receives 16%.
3. After minting the item, log in with the wallet of another collaborator.
4. Then click open the detail page of the item. For example this one https://versum.xyz/token/versum/4401
5. There ia no option to accept collaboration so the item naccot be swapped. There is also no notification warning about the collab item in the upper right corner.

**Expected behavior**
After logimg in with another collaborator's wallet and opening the page 
https://versum.xyz/token/versum/4401
 I would have expected to find a button to accept the collaboration for this item, for.example between the cover image and the icons of the collaborators as mentioned on the discord

**Screenshots**

![unknown](https://user-images.githubusercontent.com/84919649/150708823-539a5979-6aa0-4a0f-a7cd-d8aebd51cc52.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: mozilla firefox / google chrome
- Version: firefox: 96.0.2 (64-Bit) / chrome 97.0.4692.71 (Offizieller Build) (64-Bit)

**Additional context**
Since minting the items about 2 days ago the button has not appeared yet.

**Comment by andrevenancio** [comment]
hi, thanks for reporting this issue. I'm looking into this

**Comment by andrevenancio** [comment]
this has been fixed.
