### ISSUE TITLE
Description requirement

### ISSUE THREAD

**Issue by KimLaughton** [versumstudios/report-bugs#57]
I'd rather description were not a required field - many works do not need descriptions and so additional text should not be forced.

**Comment by andrevenancio** [comment]
We do require `description` field to be filled. I also never know what to write in there personally, but its part of the TZIP21 spec which defines the metadata of our token.

**Comment by KimLaughton** [comment]
> We do require `description` field to be filled. I also never know what to write in there personally, but its part of the TZIP21 spec which defines the metadata of our token.

Ah I understand - I suppose it would be possible for the site to put a dash or similar in that part of the token if nothing is filled in when minting and then not display anything when viewing the nft?

**Comment by andrevenancio** [comment]
It would be possible to even allow it on our end, but we decided to not bypass the spec and I think the best solution for your case in particular is to add an empty space or two?

**Comment by pichiste** [comment]
@andrevenancio Couldn't we just allow it to submit as an empty string?

**Comment by KimLaughton** [comment]
I think when a site requires you to fill in a field in a form you assume that’s because the site would like to have that data rather than it being a technical thing – so if this is left as a requirement many people will feel that they ought to be writing descriptions when it isn’t actually necessary. I felt bad putting a dash for this reason.

With minting being so permanent the issue is larger than it might be elsewhere, a user might rush to come up with a description that they later regret but can't change.

**Comment by andrevenancio** [comment]
I was explaining why the description isn't optional. It's rooted on the fact that we want to follow the spec of TZIP21.

Apologies if it sounded like I was consider changing. We're not. I was simply trying to suggest something that would work for you in particular if you feel like your art doesn't need a description.
