### ISSUE TITLE
Profile cover image modifications

### ISSUE THREAD

**Issue by KimLaughton** [versumstudios/report-bugs#58]
The profile banner image at the moment isn't as elegant as I feel it could be - a 1000 pixel wide image stretched out over a wide monitor will look extremely blurry. 

I think the solution would be to allow larger images, but this could cause problems with page loading. That said, if the images look messy then perhaps they shouldn't be there? They clash with the very crisp nature of the rest of the site.

Also a small issue, at the moment it is impossible to remove the images once they have been added.

**Comment by andrevenancio** [comment]
The recommended size is the same size as twitter cover. 1500x500px

**Comment by KimLaughton** [comment]
> The recommended size is the same size as twitter cover. 1500x500px

Oh right - at the moment the upload suggests smaller, 1000x300px. Twitter however doesn't stretch the cover to full browser width so it always looks crisp and maintains the same aspect ratio.

![Screenshot 2022-01-28 160558](https://user-images.githubusercontent.com/84448816/151510482-1e5c3b97-ad16-4308-b08e-724069ca33c3.jpg)

This is how it looks on my monitor, and I don't whink wide aspects are too rare these days:

![Screenshot 2022-01-28 160743](https://user-images.githubusercontent.com/84448816/151510492-43ffb48c-c4a7-4a2b-aaaf-9b1f6c1c47bc.jpg)

Watched the 'Creative Code News' twitch convo btw - really love the thought behind the design direction in general, it's way ahead of any other NFT platform out there.
