### ISSUE TITLE
I have sold a work but the money has not been deposited in my wallet

### ISSUE THREAD

**Issue by tz1NKZxHktSNmsZ6VAujuQu21aFoeLL4j5Cw** [versumstudios/report-bugs#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
https://docs.versum.xyz/docs/versum/Verification
