### ISSUE TITLE
Add full-screen mode for code / web objects.

### ISSUE THREAD

**Issue by pyglot** [versumstudios/report-bugs#6]
**Problem**

Currently there seems to be no way to view web / code items in full-screen mode, which is a much more focused experience.

Currently the web objects live in a frame that covers the entire width and most of the height of the page. Since the objects are interactive and capture mouse scrolling this makes it sometimes very hard to scroll down to the details sections which may contain important instructions for interactive objects. 

**Solutions** 

Reduce the percentage of the width and height that web/code objects take up, and add a fullscreen button that appears briefly on any interaction with the page. This is similar to the functionality on hicetnunc.*, objkt.com and hic.af. 

The button must also appear on interactions after entering fullscreen, and [ESC] should always exit the fullscreen.

**Comment by andrevenancio** [comment]
There are several embed size options. It's up to the creator to see ide how to display this

**Comment by hberge** [comment]
Sorry I don't quite understand your reply or your reasons for this. The embed size options (aspect ratios) are not the same as a full-screen display mode. 

For all ratios fullscreen mode would maximize screen realestate and remove the clutter of browser bars. This is especially important on mobile.
