### ISSUE TITLE
collects on collab items fail due to exhausted storage

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#60]
**Describe the bug**
Items with large number of collaborators require more storage to carry out the transfer of tez to the co-authors. 

The error is `proto.011-PtHangz2.storage_exhausted.operation` It looks like the large number of collaborators is affecting the amount of storage needed for the transfers of proceeds to each collaborator via `batch_fwd_xtz` internal transaction. The default storage for a collect is 250, but the amount needed in this swap is 1244. Temple doesn't allow you to edit the storageLimit when it hits this error.

![image](https://user-images.githubusercontent.com/510285/151361819-3fc29953-2c08-47e4-b90a-d7b5a93d85a0.png)

Simulation shows amt of storage needed:
![image](https://user-images.githubusercontent.com/510285/151362446-3b5e698d-87d9-4c8f-9a3d-cb6072f5960d.png)

Suggestion: for a collect_swap, set the storage limit based on: `250 + (number_of_collaborators * 100)`

**To Reproduce**

1. https://versum.xyz/token/versum/4383
2. collect swap 

**Expected behavior**
You can collect the swap

**Comment by andrevenancio** [comment]
Thanks! I'll solve this today!

**Comment by andrevenancio** [comment]
this is only to withdraw a single token right? Because I noticed if you go to a swap from the Market tab on the token page, and you are allowed to buy more than 1 token from a advanced swap, the price calculation is incorrect. visible [here](https://github.com/versumstudios/versum.xyz/blob/main/src/components/modals/swap-collect/index.tsx#L62) any suggestions for a fix is appreciated! @skenaja

**Comment by skenaja** [comment]
Same issue affects `accept_offer` on large collab items too

**Comment by andrevenancio** [comment]
So this is probably an issue that happens on every type of trade...

**Comment by andrevenancio** [comment]
Wouldn't it be better to calculate the storageLimit https://tezostaquito.io/docs/estimate/ and then use that estimate instead of jiggle with the creators number? because there might be other factors? @skenaja

**Comment by skenaja** [comment]
Mine was a quick rule of thumb. Taquito should be a more accurate amount, but it does an extra RPC call to simulate the tx under the hood.

**Comment by andrevenancio** [comment]
this should be fixed closing for now
