### ISSUE TITLE
I can't verify my profile

### ISSUE THREAD

**Issue by MarVin-69** [versumstudios/report-bugs#61]
**Describe the bug**
I have already connected with my wallet (Kukai Wallet), I waited the 24h informed, but I still couldn't get my verification.
My data in Tezos Profiles is all up to date and online.

**Expected behavior**
Even waiting for the given time, I couldn't get my verification.
I've tried logging out and back in with my wallet, clearing my machine's cache and nothing works.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser : Chrome
- Version :  97.0.4692.99

**Additional context**
I believe that there must be some inconsistency in the system that is not allowing my verification

**Comment by skenaja** [comment]
@MarVin-69 Please provide your versum profile address

**Comment by MarVin-69** [comment]
Hi, good morning
Here is my profile adress:
https://versum.xyz/user/tz1TFhjdZJiKH7JwJ1sVSRCbXMyadrN5F1fU

**Comment by skenaja** [comment]
You're verified now!
