### ISSUE TITLE
My MTRIA balance is equal to ZERO

### ISSUE THREAD

**Issue by MarVin-69** [versumstudios/report-bugs#62]
**Describe the bug**
I got my verification in Versum, but when I try to minted something, an error message appears...
I believe it is due to the fact that my MTRIA balance is equal to ZERO.
How do I resolve this?

**Expected behavior**
As they say in the help file, when connecting your wallet for the first time, you would get MTRIA, but that didn't happen for me...
So I think there must have been a problem both with my verification (which has already been resolved) and with the MTRIA airdrop...

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 97.0.4692.99

**Comment by skenaja** [comment]
https://docs.versum.xyz/docs/versum/Materia

Depending on your previous activity, It's possible that your wallet hasn't isn't eligible for Materia yet. If you need to mint now, you can buy a small amount from quipuswap or spicyswap. Just 0.01 is needed to mint.

- Spicyswap: https://spicyswap.xyz/#/app
- Quipuswap: https://quipuswap.com/swap?to=KT1KRvNVubq64ttPbQarxec5XdS6ZQU4DVD2_0&from=tez
