### ISSUE TITLE
Ended timed swaps remain as active

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#66]
Issues/feedback with timed swaps:

- swaps that have passed the end time of the swap still show as available eg https://versum.xyz/token/versum/7917. if you try to collect, you get a "this transaction will fail" wallet error, with "prim(unit)" failure reason. 
- these swaps still show as "active" in the market contract bigmap 75634

```
{"id":17445879,"active":true,"hash":"exprv2rApzrsbNmsmieKswkKXVABrG4txtZbB33Wt6yNVQyEhGAc1E","key":"17795",
"value":{"token":{"nat":"7917","address":"KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW"}, 
"seller":"tz1gF9HGfPfJoxE9Lf1LMBM5tGYD93oWH8hE","currency":null,"burn_on_end":true,
"ending_time":"2022-02-02T14:25:05Z","require_verified":false,"token_left_amount":"26","collect_max_per_tx":"2",
"token_start_amount":"99","ending_price_in_nat":"0","starting_price_in_nat":"0"},"firstLevel":2080748,
"lastLevel":2083198,"updates":69}
```

- if they are the cheapest swaps, they still show up as the primary option to collect from on the item display big collect button.

Expected results:
- shouldn't be able to collect an active swap past its end time
- UI should show that the swap time has expired

**Comment by skenaja** [comment]
https://discord.com/channels/839401288155529246/839401288155529250/938576652118667304
Suggestions:

> cancel burns them, we should rename it to "complete burn"
> We should perhaps modify it so anyone can complete the burn of such a swap after the time is up
> Maybe award some Materia if you beat the seller (which is likely the minter) to it

**Comment by andrevenancio** [comment]
Testing it with: https://versum.xyz/token/versum/28

**Comment by andrevenancio** [comment]
This has been fixed. Awaiting deployment.

If a swap had a ending time, and that ending time has been reached, it can't be selected as the "cheapest" options, and the copy instead of being "cancel swap" is "conclude swap"
