### ISSUE TITLE
BUG VERSUMSimulation error: Unrecognized error: Uncaught error in preapply

### ISSUE THREAD

**Issue by baltaZarGarden** [versumstudios/report-bugs#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baltaZarGarden** [comment]
Simulation error: Unrecognized error: Uncaught error in preapply message for Versum

**Comment by andrevenancio** [comment]
Hi @baltaZarGarden When you submit an issue there is that text above as an example on how to populate the issue with as much information as you can so we can take steps towards reproducing your issue and finding a solution. You can always edit it.

Is there any information you can provide like:
What operation were you doing? buying a token? selling a token?
steps to reproduce?
