### ISSUE TITLE
Unable to mint.

### ISSUE THREAD

**Issue by raynt** [versumstudios/report-bugs#7]
**Describe the bug**
Unable to mint with verified account and holding Materia.

**To Reproduce**

Uploaded .MP4 (Tested file sizes between 31mb and 57mb) Should list max file sizes on page.
Filled in required minting form information.

**Expected behavior**
Clicked on the Black Mint button which turned and stayed white but nothing happens. No wallet trigger or error message. Nothing happens in the console then get error message for time out. Screenshots attached.

**Screenshots**
![Screen Shot 2022-01-13 at 10 11 05 AM](https://user-images.githubusercontent.com/17106015/149357745-c8d494b4-8e1f-4584-b255-6f07c530ff1f.png)
![Screen Shot 2022-01-13 at 10 11 54 AM](https://user-images.githubusercontent.com/17106015/149357756-e48da8ba-b4b3-444f-b282-903ce61bead6.png)

**Desktop (please complete the following information):**

- OS: Catalina 10.15.7
- Brave
- Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64)

**Comment by andrevenancio** [comment]
Try to logout and login again. Normally it helps when wallet isn't popping up
