### ISSUE TITLE
Use /boards across all boards links

### ISSUE THREAD

**Issue by felirami** [versumstudios/report-bugs#70]
I would suggest to use /boards across all links so instead of having /board/random we have /boards/random so when people remove the "random" part they can see the whole list of boards in versum, as of now if you use /board it shows a 404 error.

**Comment by andrevenancio** [comment]
Its a bit semantics but `/boards` is plural means more than one. and `/board/random` indicates that you are looking at 1 single board called "random".

I could to a redirect from `/board` to `/boards` though.

**Comment by andrevenancio** [comment]
after some consideration we decided not to implement this as it affects our url structure.
