### ISSUE TITLE
Add custom image thumbnail on boards

### ISSUE THREAD

**Issue by felirami** [versumstudios/report-bugs#71]
I've made a 20x20 small "collection" and added them to a board, once it shows in the /boards the images are all pixelated in a bad way, would be dope if we could add a custom image thumbnail so it looks better, could it even be a gif image! 

Example image https://cdn.discordapp.com/attachments/859349846892085250/942177002180472882/unknown.png

**Comment by andrevenancio** [comment]
will look into this tomorrow! sorry it took so long to spot this

**Comment by andrevenancio** [comment]
Can you provide me a link to that board?

**Comment by felirami** [comment]
There you go andre https://versum.xyz/board/yatefqfwn

**Comment by andrevenancio** [comment]
fixed
