### ISSUE TITLE
Photosensitive alert to always be displayed

### ISSUE THREAD

**Issue by felirami** [versumstudios/report-bugs#73]
I believe is really important to show the photosensitive warning and one issue I had is that I didn't know where it was because if you scroll just once or a little bit it dissapears.

I would suggest to make it not dissapear and also maybe make the text bolder or more noticeable.

Example:
- No scroll https://media.discordapp.net/attachments/859349846892085250/942188690174803968/photosensitive1.png
- One scroll https://media.discordapp.net/attachments/859349846892085250/942188689986027550/photosensitive2.png

**Comment by andrevenancio** [comment]
After some consideration we are not going to implement this at this time.
