### ISSUE TITLE
Can't mint (transaction failed)

### ISSUE THREAD

**Issue by joker6616renger** [versumstudios/report-bugs#74]
**Describe the bug**

**To Reproduce**

1. Go to Mint menu
2. Click on Mint button
3. Scroll down to sign transaction
5. {
  "props": {
    "amount": "1",
    "infusions": [],
    "max_per_address": 0,
    "metadata": {
      "valueMap": {},
      "keyMap": {}
    },
    "no_transfers_until": null,
    "req_verified_to_own": false,
    "royalties": "100",
    "splits": [
      {
        "address": "tz1P17DvEJeuB2ZHS3A3NgkMsXN5ejNX8bzY",
        "pct": "1000"
      }
    ]
  },
  "send": {
    "amount": 0,
    "storageLimit": 1000
  },
  "error": {
    "name": "TransactionInvalidBeaconError",
    "title": "Transaction Invalid",
    "message": "[TRANSACTION_INVALID_ERROR]:The transaction is invalid and the node did not accept it.",
    "description": "The transaction is invalid and the node did not accept it."
  },
  "message": "Error signing transaction on mint"
}

**Expected behavior**
to be fixed

**Desktop (please complete the following information):**

- OS: Window 10 pro
- Browser Chrome
- Version  98.0.4758.82(official) 64bit

**Additional context**

**Comment by andrevenancio** [comment]
Its likely an issue with your selected RPC node. Are you able to change and choose another and try again?

**Comment by hansverhaegen** [comment]
I have the same error. But apparantly the minting went through. I see my tokens appear in my profile. When I close the error message, the confirm box briefly appears, immediately goes away (without me confirming) and then I land on a new minting screen.

**Comment by hansverhaegen** [comment]
hmm, now it hangs on signing contract:
![Schermafbeelding 2022-03-11 om 13 51 37](https://user-images.githubusercontent.com/97689698/157870082-b12f806e-cc4b-4e1c-896b-b0c5527174c7.png)

**Comment by hansverhaegen** [comment]
Waited 10 minutes. Then skipped and tried again. Works again. Soem kind of temporary connection with Temple wallet?

**Comment by hansverhaegen** [comment]
For me, seems to be ok again.
