### ISSUE TITLE
14 Feb 2022 Item swapped and still invisible on my profile 1hr 6min later

### ISSUE THREAD

**Issue by flintpope** [versumstudios/report-bugs#77]
Item swapped and still invisible on my profile 1hr 6min later
Click https://versum.xyz/user/tz1Yq6uCkMiAbk3DuWmEmEtEL4c5sCnwx2Ec

Try and see token called CENTRAL PARK ANOMALY

Token number 9 of CREATED doesn't show
![Screenshot 2022-02-14 at 19 54 17](https://user-images.githubusercontent.com/34174964/153936613-1c5d8bfb-4874-4b96-a0a5-58c94d3b5623.png)

**Desktop (please complete the following information):**

- OS: [Mac 10.14.6]
- Browser [chrome 92.0.4515.107 and safari 14.1.2]

**Additional context**
Something I sold on auction hasn't shown up an hour later in recipients wallet but transaction has taken place in my walet (kukai) and on his tzkt page

**Comment by andrevenancio** [comment]
Should be fixed. The indexer crashed

**Comment by flintpope** [comment]
Yes it is now. thanks!
________________________________

**Comment by apauf** [comment]
A week ago I cancelled the price of 6 copies of "https://versum.xyz/token/versum/17305", my wallet says the transaction was successful. (Apr 11, 09:04:14 AM) 
The change does not appear on my Versum profile, so I cannot burn or reprice these 6 copies. 
Thank you in advance.

**Comment by flintpope** [comment]
Not me!
________________________________
