### ISSUE TITLE
Unable to Click Mint Button

### ISSUE THREAD

**Issue by dupesdidit** [versumstudios/report-bugs#78]
**Describe the bug**
I am unable to mint any art on the platform I MTRIA in my wallet and I have also tried numerous times to mint a video that includes audio. any assistance would be greatly appreciated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by skenaja** [comment]
Please provide more information to help diagnose the issue:
- your wallet address
- any error messages shown

I'll re-open when this is done

**Comment by dupesdidit** [comment]
thanks so much for the reply here is my tezos wallet address

tz2N7bxD26N4WGTfxrts6E5kPZPNAarSwiCk

also no i don't receive any errors i have made attempts with my crhomebook
and my macbook even my cell phone

thank you

**Comment by skenaja** [comment]
You need to have a verified account prior to minting - please check out https://docs.versum.xyz/faq/verification/ and your account Settings page on Versum to see if there's a button to verify the account.

You need at least 2 sources on tzprofiles, so consider adding your Twitter or Discord account to your list of proofs:
https://tzprofiles.com/view/tz2N7bxD26N4WGTfxrts6E5kPZPNAarSwiCk

**Comment by dupesdidit** [comment]
Ok, I have tried that but will go through the process one more time and ill
see if that works

Thanks
