### ISSUE TITLE
Mint failure with .mp4 file (95.5 MB) payload during pinning phase (Chrome) and prior to encoding (Firefox)

### ISSUE THREAD

**Issue by lipsumart** [versumstudios/report-bugs#79]
**Describe the bug**

I receive a "metadata undefined" error when trying to mint a 95.5 MB .mp4 file during the pinning phase, after a very long encoding phase.

**To Reproduce**

1. Go to versum.xyz.
2. Click on the 'Log in' button.
3. Click on 'Mint'.
4. Fill relevant information (name, description, tags, editions, royalties), uploading an .mp4 file (95.5 MB) as payload. 
5. Click on the 'Mint' button at the bottom of the page.

CHROME:
6. Wait for minting process: encoding takes a long time and, during the IPFS pinning phase, the page throws an error:
{
  "message": "metadata undefined"
}.

FIREFOX:
6. Minting process starts for a few seconds, then throws the following error:
{
  "message": "An error has occurred whilst trying to extract the mint data"
}

**Expected behavior**

I expected the NFT to be minted as normal.

**Screenshots**
![metadataundefined](https://user-images.githubusercontent.com/87296806/153979428-4892cae1-f15b-4a2d-9318-8392285aab9d.JPG)

![errorwhilst](https://user-images.githubusercontent.com/87296806/153979538-1035f1ef-9723-4062-a4a3-01af58a0b76b.JPG)

**Desktop (please complete the following information):**

- Windows 10
- Google Chrome Version 98.0.4758.82 (Official Build) (64-bit), Firefox 97.0 (64-bit)

**Additional context**

This was tried with VPNs and AdBlocker off after that was suggested by another user.

**Comment by andrevenancio** [comment]
thanks for reporting. we changed the way our mint is structured, this error should be fixed, but let us know if not.
