### ISSUE TITLE
Doc edit link broken

### ISSUE THREAD

**Issue by LeonNicholls** [versumstudios/report-bugs#8]
**Describe the bug**
At the bottom of the docs pages at https://docs.versum.xyz/docs/versum/FAQ, there is a link to edit the page: https://github.com/versumstudios/docs.versum.xyz/edit/main/src/docs/versum/Materia.mdx
When you click on the link, Github displays a 404 error.

**To Reproduce**

1. Go to 'https://docs.versum.xyz/docs/versum/FAQ'
2. Click on 'Edit this page on Github'
3. See 404 error

**Expected behavior**
A way to edit the page on github.

**Screenshots**
<img width="744" alt="github404" src="https://user-images.githubusercontent.com/564979/149364317-2ef712db-2d50-4c17-a07b-fb5eb48f89dd.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
This is correct at the time of your issue the docs repository was private. It's public now
