### ISSUE TITLE
make an offer

### ISSUE THREAD

**Issue by wildmml** [versumstudios/report-bugs#81]
Tried to make an offer.
<img width="881" alt="Снимок экрана 2022-02-17 в 00 35 47" src="https://user-images.githubusercontent.com/86856313/154369142-ba6b27e8-a975-4bb2-8da2-3a5b36f15f14.png">

{
  "props": {
    "0": "KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW",
    "1": 13159,
    "currency": null,
    "price_in_nat": 0,
    "require_verified": false,
    "token_amount": 1
  },
  "send": {
    "amount": 3000000,
    "mutez": true,
    "storageLimit": 250
  },
  "error": {
    "name": "ParametersInvalidBeaconError",
    "title": "Parameters Invalid",
    "message": "[PARAMETERS_INVALID_ERROR]:Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.",
    "description": "Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again."
  },
  "message": "Error on make_offer"
}

**Comment by andrevenancio** [comment]
Hi @wildmml was this on an advanced swap? It seems like this token has been burned https://versum.xyz/token/versum/13159 So its possible the user burned it and because we have a 30second cache you tried to do this while the token was visible on our platform but the token was already burned.
