### ISSUE TITLE
Versum buy limit issues 

### ISSUE THREAD

**Issue by x3r0ne** [versumstudios/report-bugs#82]
Versum has a feature to limit the amount of swaps a wallet can do for an objkt you are selling but seems to have a simple run around. The buyer can purchase an objkt that has a buy limit and then place it for swap allowing them to buy another of the same objkt. Then they can remove the first objkt from swap giving them 2 copies of an objkt with a buy limit. 

https://versum.xyz/token/versum/12607       is the token in question. 

These are the 4 wallets that performed the buy limit run around on this objkt. The last wallet (***) is a verified user with a check

tz1PK5aqTegwKU46AL781A53ik4x2dKA5yr4
tz1bJjsvg8p1LVkivf8KBrts7ARfQ6K7aXYa
tz1KowuphA198vtBconkr1FjgsfoDah6kjgL

***tz1PbZgXgczEiBg9NGcJoX7QVV9Xs74SeU9U***

**Comment by andrevenancio** [comment]
Hi @x3r0ne `objkt` is the token name for hicetnunc. On versum the token name is called `item`.

The mechanics you described are possible and there isn't anything we can do about it. Once you put a token on the market it leaves your wallet. so you dont technically own it. the versum market does. 
but thanks for reporting. appreciate you taking the time!

**Comment by x3r0ne** [comment]
Then one might infer that this function is nothing more than a gimmick
intended to aquire more users. I say this because the tool does nothing to
deter individuals who are already going to manipulate the system. So here I
am, a user, telling others about this cool new feature that could help
bring some stability to artist drops when in actuality a hack is already
being utilized.

It may also highlight how ineffective your verification system is since
someone with a ✔ was among the users manipulating the inteded function of
the TOKEN.

A good UI will only get you so far team. If nothing functions we'll all
just migrate to the next platform that promisses improvements and Versum
will become another relic of last week.

I know the solutions take longer to implament then they do to identify but
that last email screams "nothing we can do about it." I hope that isn't the
case.

Sincerely

01

**Comment by andrevenancio** [comment]
I'm sorry you feel that way.

I think you might be misinterpreting the feature. The feature is `max per wallet`. No wallet can hold more than the amount defined by the artists and that works as intended.

Where I think you might be confused is that you're interpreting this as a max per user. 

Lets take this example:
1) Artists defines a `max per wallet` of 2 token editions.
2) You buy 2
3) You sell them both.

Should you not be allowed to buy it again? You dont own it anymore...? So, you are allowed to buy and hold 2 more per wallet.

This feature works as advertised and as designed.
Thanks for your feedback

**Comment by veqtor** [comment]
There is a fix coming for this... More info later
It is complimentary to current methods to deter this behaviour. It will completely make it impossible to work around the constraints but at a cost.

**Comment by veqtor** [comment]
> tz1PK5aqTegwKU46AL781A53ik4x2dKA5yr4 tz1bJjsvg8p1LVkivf8KBrts7ARfQ6K7aXYa tz1KowuphA198vtBconkr1FjgsfoDah6kjgL
> 
> _**tz1PbZgXgczEiBg9NGcJoX7QVV9Xs74SeU9U**_

can you provide info on these transactions?

**Comment by x3r0ne** [comment]
Great example but how does that work for me creating a max of 1 per wallet
and then 4 people end up with 2 per wallet?

**Comment by andrevenancio** [comment]
There are 2 limits that you as an artist can do:

`max-per-wallet` and `max-per-transaction`.

`max per wallet`: which is the one I thought you were talking about, only allows for X amount of tokens to be in a wallet at a time (as I try to explain above). This limit can only be setup by the artist on mint.

`max per transaction` allows you to define a max amount of tokens that can be collected on a single transaction. This can be defined by both the artist or by any token holder putting it up on the market. This second method doesn't stop users from piling up multiple editions of one particular token.

Looking at your Discord [message](https://discord.com/channels/839401288155529246/930994018911924235/943500147764101151), that token [12607](https://versum.xyz/token/versum/12607)
 doesn't have a `max-per-wallet`, which means you didn't add it at mint. If it did, that information would have shown on the `Info` tab on the token detail page like the image below:
 
<img width="453" alt="Screenshot 2022-02-21 at 17 35 21" src="https://user-images.githubusercontent.com/1734502/155004760-d5945279-5be9-4c6e-a242-298355871535.png">

I hope it helps clear things up.

**Comment by veqtor** [comment]
Usually creators would choose 2-3 max per wallet on mint and then 1 max-per-transaction on swap.
There is a very very involved way to work around max per wallet and max per transaction but we've seen just one user apply it that we banned, I thought you were talking about this.
