### ISSUE TITLE
Search by artist

### ISSUE THREAD

**Issue by flintpope** [versumstudios/report-bugs#83]
My collectors from teia say they dislike versum because they can't find the artists they like. I also find it awkward to follow familiar names of artists I enjoy ( I collect occasionally too) unless I fish out their twitter page and see if they may have linked to their versum profile

Perhaps include a dropdown under the "explore" button to "search by artist"

The alternative I have considered involves going elsewhere to find who is on versum as desc above

I am aware that your approach is designed to offer the user a new discovery experience (your BOARDS are brilliant for this) but sometimes you KNOW what you want and you can;t find it.

Great site though! I have dropped teia now as it is TBH amateur cf yours

**Comment by andrevenancio** [comment]
Hi @flintpope Thanks for your feedback. this is on our todo list, but we're prioritising some bug fixes. We'll get around to add it over the next few days.

**Comment by flintpope** [comment]
Cool.

Thanks!
________________________________

**Comment by andrevenancio** [comment]
This has been implemented.
