### ISSUE TITLE
NFT not displayed

### ISSUE THREAD

**Issue by younesjam** [versumstudios/report-bugs#84]

**Comment by skenaja** [comment]
Please can you provide some more details @younesjam - 

1) which NFT? Can you provide the versum URL?
2) are you using a mobile device or laptop/desktop?
3) which browser? Chrome, Firefox, Safari etc
4) where there any error messages?

I'll re-open the ticket when further details are supplied

**Comment by younesjam** [comment]
thank you
After 3 hours the problem was solved on its own
