### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by yogapratamah** [versumstudios/report-bugs#86]
**Is your feature request related to a problem? Please describe.**
The search box will help us to find collections, art, or artists

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrevenancio** [comment]
duplicate of [https://github.com/versumstudios/report-issues/issues/83](https://github.com/versumstudios/report-issues/issues/83)

**Comment by andrevenancio** [comment]
closing it, but you can follow progress on #83
