### ISSUE TITLE
An error has occurred whilst trying to upload your token

### ISSUE THREAD

**Issue by Pollomoolokki** [versumstudios/report-bugs#88]
**Describe the bug**

**To Reproduce**

1. Go to 'mint'
2. Click on mint

**Expected behavior**

I expected to mint

**Screenshots**

**Desktop (please complete the following information):**

Ubuntu 20.04.4 LTS

Mozilla Firefox 97.0

**Additional context**
{
  "fileName": "https://versum.xyz/_next/static/chunks/964.8cc7d317dab1b9d7.js",
  "lineNumber": 1,
  "columnNumber": 3546,
  "message": "An error has occurred whilst trying to upload your token"
}

**Comment by andrevenancio** [comment]
Earlier today there was an issue with Infura changing their API. Can you confirm if this is still happening?

**Comment by Pollomoolokki** [comment]
Cannot confirm - It seems to be fixed now. I was able to mint
