### ISSUE TITLE
stack error

### ISSUE THREAD

**Issue by flintpope** [versumstudios/report-bugs#89]
{
  "stack": "Error: Method Not Allowed\n    at https://versum.xyz/_next/static/chunks/964.8cc7d317dab1b9d7.js:1:3546\n    at l (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92495)\n    at Generator._invoke (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92283)\n    at Generator.P.forEach.e.<computed> [as next] (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92918)\n    at l (https://versum.xyz/_next/static/chunks/964.8cc7d317dab1b9d7.js:1:831)\n    at u (https://versum.xyz/_next/static/chunks/964.8cc7d317dab1b9d7.js:1:1034)",
  "message": "An error has occurred whilst trying to upload your token"
}

**Comment by andrevenancio** [comment]
Thanks for reporting. there was an update to infura's API that broke minting.

It should be resolved now
