### ISSUE TITLE
No Mitra and "Following" appears

### ISSUE THREAD

**Issue by Anutk** [versumstudios/report-bugs#91]
**Describe the bug**
There is no materia to claim and I cannot figure out where to get it from. I've tried to find tech support but since I cannot find it I'm writing it here. I've connected a wallet, even bought an artwork, verified one account, so that works. But I still have no mitra needed to mint so I cannot mint my NFTs. Also when I click follow someone or a project it doesn't appear in my "following" - I cannot see who I am following. I would be super grateful for your help and if you know a way to get in touch with tech support that would be amazing.

Also I tried to get into discord but it says "invite invalid". - I have an account on discord and it works, I don't understand why this doesn't. I am using Chrome browser.

**To Reproduce**

**Expected behavior**
As described above.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 98.0.4758.102

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
If you are not awarded materia then you need to purchase it from anyone selling it on quipuswap. Please read through docs.versum.xyz for more info.
