### ISSUE TITLE
layout issue

### ISSUE THREAD

**Issue by ChrisFollows** [versumstudios/report-bugs#93]
**Describe the bug**
The layout on profile page is all squashed over to the left https://versum.xyz/user/tz1cmorCw9xzeLt5JKaQJvwFV7Dvf1vG2V4g/created

**To Reproduce**

1. Go to https://versum.xyz/user/tz1cmorCw9xzeLt5JKaQJvwFV7Dvf1vG2V4g/created
3. Scroll down to the work on display

**Expected behavior**
The normal layout on profile page 

**Screenshots**

**Desktop (please complete the following information):**

- Browser chrome and brave
- Version [Version 1.36.111](https://brave.com/latest/)
![Capturewww11](https://user-images.githubusercontent.com/22909526/157682524-822fe1d5-c3a7-4a51-8df8-23652cb4dda6.JPG)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
Hi Chris! This is an issue that flexbox causes where they try to squash tokens on the left to fill that space before filling the one on the right. I'm aware of this, will fix soon. closing for now.
