### ISSUE TITLE
Error on cancel_swap

### ISSUE THREAD

**Issue by alohamoji** [versumstudios/report-bugs#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img width="1283" alt="Screen Shot 2022-03-17 at 8 33 05 AM" src="https://user-images.githubusercontent.com/85047924/158837830-5f5049fe-f4d9-4570-bb9b-e9384240fbfe.png">

**Comment by andrevenancio** [comment]
Hi, normally any Beacon Error has to to with taquito/beacon which is a layer in between versum and your wallet. Try logging out and logging in again, sometimes the nodes handling the operations fail (uncommon, but possible).
