### ISSUE TITLE
Missing whitespace in warning message

### ISSUE THREAD

**Issue by emiliobasualdo** [versumstudios/report-bugs#96]
**Describe the bug**
A warning massage is placed in https://versum.xyz/mint?le=true when the user has **NO** MTRIA.
The message is missing a whitespace

**To Reproduce**
1. Have an account with no MTRIA
2. Go to https://versum.xyz/mint?le=true 
3. Read warning: ` You must have at least 0.01 Materia to mint (you have 0MTRIA). Read more on`
4. 
<img width="782" alt="Screen Shot 2022-03-20 at 15 57 59" src="https://user-images.githubusercontent.com/12802164/159178230-c54d41ce-375d-4221-9047-70299bfc37ce.png">

**Comment by andrevenancio** [comment]
Thanks! sorted will deploy on next
