### ISSUE TITLE
`An error has occurred whilst trying to upload your token` error

### ISSUE THREAD

**Issue by cruacl** [versumstudios/report-bugs#97]
**Describe the bug**

`{ "stack": "TypeError: Failed to fetch\n at https://versum.xyz/_next/static/chunks/pages/_app-1fedbf2ee1b4333c.js:1:712890\n at https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:15013\n at l (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92495)\n at Generator._invoke (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92283)\n at Generator.P.forEach.e.<computed> [as next] (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92918)\n at L (https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:11510)\n at c (https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:11713)", "message": "An error has occurred whilst trying to upload your token" }`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrevenancio** [comment]
Hi @cruacl what is your wallet address, which token are you trying to purchase, and could you please edit your description to remove the "instructions" if they aren't relevant? they are supposed to be an example on how you should describe a bug to help us replicate your issue. With the information provided I am unable to replicate it.
