### ISSUE TITLE
Cancel Swap 

### ISSUE THREAD

**Issue by apauf** [versumstudios/report-bugs#99]
A week ago I cancelled the price of 6 copies of "https://versum.xyz/token/versum/17305", my wallet says the transaction was successful. (Apr 11, 09:04:14 AM)
The change does not appear on my Versum profile.
Thank you in advance.

**Comment by andrevenancio** [comment]
Hi @apauf sorry I haven't seen this earlier.

Its possible that you were having some cache issues and its now been updated?

**Comment by apauf** [comment]
Hi @andrevenancio !
I don't know, nothing has been updated! 
The problem persists, but only on the VERSUM page.
The transaction is visible on objkt.com! 
https://objkt.com/asset/versum_items/17305

**Comment by apauf** [comment]
Hi @andrevenancio ! 
The problem is solved, thanks!
